"""Shared route construction and Q1 solver interfaces."""

from .alns import ALNSRunResult, Q1ALNSConfig, improve_q1_alns
from .baseline import solve_q1_baseline
from .cache import SolverCache
from .data import load_problem_data
from .evaluator import evaluate_route
from .exporter import export_q1_solution, load_q1_solution
from .improve import improve_q1_batch_relocation, improve_q1_route_ejection, improve_q1_savings
from .models import SolverConfig
from .physics import LegPhysics
from .q1_exact import (
    HighsMasterResult,
    PatternMipStart,
    audit_master_symmetry,
    build_frozen_incumbent_start,
    canonical_allocation_pattern,
    materialize_pattern_start,
    solve_highs_pattern_master,
)
from .q1_or import (
    EliteRoutePool,
    Q1MasterConfig,
    Q1MasterResult,
    Q1RestrictedLPResult,
    Q1TargetedRepairResult,
    collect_elite_route_pool,
    exact_targeted_repair,
    route_elimination_audit,
    route_identity,
    solve_restricted_lp,
    solve_route_pool_master,
    targeted_route_indices,
)
from .q1_pricing import (
    PRICING_TOL,
    ArcBranchRow,
    ExactPricingResult,
    ExactRouteColumn,
    FullspaceRmpLPResult,
    allocation_reward,
    aggregate_arc_usage,
    choose_fractional_arc_branch,
    column_arc_counts,
    column_reduced_cost,
    branch_column_reduced_cost,
    exact_pricing,
    initial_exact_columns,
    pricing_result_to_column,
    solve_exact_column_rmp_lp,
    solve_fullspace_rmp_lp,
)
from .q1_branch_price import (
    CERT_TOL,
    INTEGER_TOL,
    LP_FEAS_TOL,
    ExactColumnMasterResult,
    BranchRmpLPResult,
    BranchNode,
    FullyPricedIteration,
    FullyPricedNodeResult,
    exact_column_start_from_pattern_start,
    load_generated_exact_columns,
    materialize_exact_column_solution,
    solve_exact_column_integer_master,
    solve_branch_rmp_lp,
    solve_branch_phase_one_rmp_lp,
    solve_fully_priced_node,
)
from .technical_stops import augment_service_sequence

__all__ = [
    "ALNSRunResult",
    "augment_service_sequence",
    "evaluate_route",
    "export_q1_solution",
    "EliteRoutePool",
    "ExactPricingResult",
    "ExactRouteColumn",
    "ExactColumnMasterResult",
    "BranchRmpLPResult",
    "BranchNode",
    "FullyPricedIteration",
    "FullyPricedNodeResult",
    "ArcBranchRow",
    "FullspaceRmpLPResult",
    "LegPhysics",
    "HighsMasterResult",
    "load_q1_solution",
    "load_problem_data",
    "improve_q1_alns",
    "improve_q1_savings",
    "improve_q1_batch_relocation",
    "improve_q1_route_ejection",
    "Q1ALNSConfig",
    "Q1MasterConfig",
    "Q1MasterResult",
    "Q1RestrictedLPResult",
    "Q1TargetedRepairResult",
    "PatternMipStart",
    "PRICING_TOL",
    "LP_FEAS_TOL",
    "INTEGER_TOL",
    "CERT_TOL",
    "allocation_reward",
    "aggregate_arc_usage",
    "audit_master_symmetry",
    "build_frozen_incumbent_start",
    "canonical_allocation_pattern",
    "column_reduced_cost",
    "branch_column_reduced_cost",
    "column_arc_counts",
    "choose_fractional_arc_branch",
    "exact_pricing",
    "initial_exact_columns",
    "exact_column_start_from_pattern_start",
    "load_generated_exact_columns",
    "materialize_exact_column_solution",
    "materialize_pattern_start",
    "pricing_result_to_column",
    "collect_elite_route_pool",
    "exact_targeted_repair",
    "route_elimination_audit",
    "route_identity",
    "SolverCache",
    "SolverConfig",
    "solve_q1_baseline",
    "solve_restricted_lp",
    "solve_route_pool_master",
    "solve_highs_pattern_master",
    "solve_fullspace_rmp_lp",
    "solve_exact_column_rmp_lp",
    "solve_exact_column_integer_master",
    "solve_branch_rmp_lp",
    "solve_branch_phase_one_rmp_lp",
    "solve_fully_priced_node",
    "targeted_route_indices",
]
